### ISSUE TITLE
Fish needs auto KEYX on decrypt error

### ISSUE THREAD

**Issue by bdrewery** [wraith/wraith#74] opened 2013-11-20 14:31 UTC
## in query

<pre>
08:29:16 [bryan] auth? *
08:29:20 -!- FiSH: Sent my DH1080 public key to wraithtcl, waiting for reply ...
08:29:21 -!- FiSH: Key for wraithtcl successfully set!
08:29:22 [bryan] auth? *
08:29:25 [wraithtcl] auth. wtest2 *
</pre>

## on bot

<pre>
 [14:29:16] (wtest2) [bryan!bryan@host] +OK O.czD.Jf8wN. 
</pre>

**Comment by ducch** [comment] 2015-02-07 22:39
isn't this a duplicate of #23?

**Comment by bdrewery** [comment] 2016-02-15 19:53
e21e1336e4972b097389507f9ff9ddfd08fb6dc5 should have covered it

**Comment by bdrewery** [comment] 2016-02-15 19:56
Ah, not quite.

**Closed** 2016-02-15 20:05 UTC
Labels: defect
